services:
  airflow:
    build: .
    container_name: airflow
    command: airflow standalone
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark:/opt/spark_jobs
      - ./data:/opt/data
  spark:
    image: apache/spark:3.5.0
    container_name: spark
    volumes:
      - ./spark:/opt/spark_jobs
      - ./data:/opt/data
    command: tail -f /dev/null
